"""
Base Adapter for Data Collector Hub v1.0

Assumptions:
- DataItem is the standard data container
- fetch() is mandatory, normalize() is optional
- normalize() output is weakly structured (no strict field validation)
- Pipeline generates unique_key, not the plugin
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


@dataclass
class DataItem:
    """
    Standard data container for collected items.

    Attributes:
        source: Data source identifier (e.g., "weibo", "newsapi")
        plugin_id: Plugin identifier (should match adapter.name)
        timestamp: Collection timestamp (when data was collected)
        data: Raw data payload
        metadata: Additional metadata about the collection
    """
    source: str
    plugin_id: str
    timestamp: datetime
    data: Dict[str, Any]
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseAdapter(ABC):
    """
    Base class for all data collection plugins.

    Subclasses must implement fetch() method.
    normalize() is optional but recommended.

    Class Attributes (required):
        name: Unique plugin identifier (lowercase_with_underscores)
        version: Semantic version (e.g., "1.0.0")
        description: Human-readable description
        author: Plugin author name
        tags: List of tags for categorization
        config_schema: Configuration schema definition
        dependencies: List of plugin dependencies (MVP: must be empty [])
        collection_mode: "full" or "incremental"
    """

    # Required class attributes
    name: str = ""
    version: str = "1.0.0"
    description: str = ""
    author: str = ""
    tags: List[str] = []
    config_schema: Dict[str, Any] = {}
    dependencies: List[str] = []  # MVP: must be empty
    collection_mode: str = "full"  # "full" or "incremental"

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize adapter with configuration.

        Args:
            config: Plugin configuration dictionary
        """
        defaults = {
            field_name: schema["default"]
            for field_name, schema in self.config_schema.items()
            if "default" in schema
        }
        self.config = {**defaults, **(config or {})}

        # Validate dependencies (MVP requirement)
        if self.dependencies:
            raise ValueError(f"Plugin {self.name}: dependencies must be empty in MVP")

        self.validate_config()

    @abstractmethod
    async def fetch(self, **kwargs) -> List[DataItem]:
        """
        Core collection method. Must be implemented by subclasses.

        Returns:
            List of DataItem objects
        """
        pass

    async def before_fetch(self) -> None:
        """
        Pre-fetch hook. Override for initialization (e.g., login, setup client).
        """
        pass

    async def after_fetch(self, items: List[DataItem]) -> List[DataItem]:
        """
        Post-fetch hook. Override for data cleaning/filtering.

        Args:
            items: Collected items

        Returns:
            Processed items
        """
        return items

    def normalize(self, raw_data: Dict[str, Any], raw_data_id: int) -> Optional[Dict[str, Any]]:
        """
        Convert raw data to normalized format.
        This is optional but recommended.

        Returns a dictionary with these recommended fields:
        - event_type: "news" | "social" | "finance" | "alert"
        - event_source: Event source name (e.g., "微博", "知乎")
        - entity: List of extracted entities (optional)
        - event_timestamp: When the event occurred
        - title: Content title/identifier (first 50 chars for dedup key)
        - payload: Standardized container for the data

        Note: unique_key is NOT returned here - it's generated by Pipeline.

        Args:
            raw_data: The raw data dictionary
            raw_data_id: ID of the raw_data record in database

        Returns:
            Normalized data dict or None if normalization fails
        """
        return None

    async def health_check(self) -> bool:
        """
        Check data source availability. Override for custom health checks.

        Returns:
            True if healthy, False otherwise
        """
        return True

    def get_default_schedule(self) -> Optional[str]:
        """
        Return default cron schedule expression.

        Returns:
            Cron expression (e.g., "*/5 * * * *" for every 5 minutes)
            or None if no default schedule
        """
        return None

    def validate_config(self) -> bool:
        """
        Validate configuration against config_schema.

        Returns:
            True if valid, raises ValueError otherwise
        """
        for field_name, schema in self.config_schema.items():
            if schema.get("required", False):
                if field_name not in self.config or self.config[field_name] is None:
                    raise ValueError(f"Required config field '{field_name}' is missing")

            # Type checking (basic)
            if field_name in self.config:
                value = self.config[field_name]
                field_type = schema.get("type")
                if field_type == "string" and not isinstance(value, str):
                    raise ValueError(f"Config field '{field_name}' must be a string")
                elif field_type == "integer" and not isinstance(value, int):
                    raise ValueError(f"Config field '{field_name}' must be an integer")
                elif field_type == "boolean" and not isinstance(value, bool):
                    raise ValueError(f"Config field '{field_name}' must be a boolean")
                elif field_type == "array" and not isinstance(value, list):
                    raise ValueError(f"Config field '{field_name}' must be an array")
                elif field_type == "object" and not isinstance(value, dict):
                    raise ValueError(f"Config field '{field_name}' must be an object")

        return True
